apiVersion: apps/v1
kind: Deployment
metadata:
  name: it21311772-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: it21311772-service
  template:
    metadata:
      labels:
        app: it21311772-service
    spec:
      containers:
        - name: it21311772-service
          image: 124355653119.dkr.ecr.eu-north-1.amazonaws.com/it21311772-service:latest
          ports:
            - name: http
              containerPort: 8002
              protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: it21311772-service
spec:
  selector:
    app: it21311772-service
  ports:
    - protocol: TCP
      port: 8002
      targetPort: 8002
  type: LoadBalancer
