apiVersion: apps/v1
kind: Deployment
metadata:
  name: it21894510-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: it21894510-service
  template:
    metadata:
      labels:
        app: it21894510-service
    spec:
      containers:
        - name: it21894510-service
          image: 124355653119.dkr.ecr.eu-north-1.amazonaws.com/it21894510-service:latest
          ports:
            - name: http
              containerPort: 8004
              protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: it21894510-service
spec:
  selector:
    app: it21894510-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8004
  type: ClusterIP
